
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  user: YWRtaW4=
  pass: MWYyZDFlMmU2N2Rm

#  $ echo -n 'admin' | base64
#  YWRtaW4=
#  $ echo -n '1f2d1e2e67df' | base64
#  MWYyZDFlMmU2N2Rm